

steps:
  - label: ":package: Install dependencies"
    commands:
      - "npm ci"
    key: install
    agents:
      queue: "nextgen-deploy-m4udev"

  - label: ":mag: Lint"
    commands:
      - "npm run lint"
    depends_on: install
    key: lint
    agents:
      queue: "nextgen-deploy-m4udev"

  - label: ":hammer: Build"
    commands:
      - "npm run build"
    depends_on: lint
    key: build
    agents:
      queue: "nextgen-deploy-m4udev"

  - label: ":test_tube: Test"
    commands:
      - "npm run test"
    depends_on: build
    key: test
    agents:
      queue: "nextgen-deploy-m4udev"

  - wait

  - wait

  - block: "Manual approval required to deploy release"
    if: build.branch == "main"
    depends_on: test
    key: release-approval

  - label: ":rocket: Release (main only)"
    if: build.branch == "main"
    depends_on: release-approval
    key: release
    commands:
      - "npm run build"
      - "npm publish"
    agents:
      queue: "nextgen-deploy-m4udev"
